### ISSUE TITLE
spawn prefabs

### ISSUE THREAD

**Issue by maxDierschke** [machinegunflows/LogiSim#10]
Hey Karl, ich habe mir deinen commit angeschaut, und es sieht gut aus, was du dort machst. Wie heute Morgen besprochen, wäre es gut, wenn wir prefabs spawnen könnten. Deshalb Solltest du dir am besten mal eine kleine Einführung in Prefabs anschauen, und dann an Stelle eines Cubes ein Wand Prefab erscheinen lassen. Der Prefab sollte nicht zu komplex sein sondern einfach nur ein Cube, der z.b. 2.3 hoch, 0.2 breit und 1 lang.

**Comment by machinegunflows** [comment]
@Karl-Christian Ist die Issue fertig? Ich schließe die erstmal. Wenn die noch nicht fertig ist bitte wieder aufmachen und im Scrum-Board ebenfalls von Done auf einen anderen Status setzen.
