### ISSUE TITLE
persist objects

### ISSUE THREAD

**Issue by maxDierschke** [machinegunflows/LogiSim#11]
Das persistieren der Objekte die in dem Floor-Planner erstellt werden, sollen in json format persistiert und wieder hergestellt werden können. Hierzu soll ein persistence service erstellt werden, der Methoden zum speichern und laden dieser Objekte erhalten soll.

**Comment by machinegunflows** [comment]
@maxDierschke Wieso bin ich hier assigned :)

**Comment by machinegunflows** [comment]
@maxDierschke Ich schließe die erstmal, weil sie sich im Done Tab befindet.
