### ISSUE TITLE
Design/ Konzept der Benutzeroberfläche im Floorplan Editor

### ISSUE THREAD

**Issue by maxDierschke** [machinegunflows/LogiSim#12]
In diesem Ticket soll festgelegt werden, wie die UI aussehen soll. Z.B. die Funktion einzelner Buttons und anderer UI Components soll hier definiert, sowie die Anordnung dieser festgelegt werden. Im optimal Fall als Mockup. Alternativ als direkte Implementierung innerhalb der Floorplanning scene (Components dann einfach ohne Funktion falls zu aufwendig). Je Component-Gruppe soll dann ein dazugehöriges Ticket angelegt werden (nicht zu granular).

**Comment by maxDierschke** [comment]
Hey Sandra, ich habe dein Mockup angeschaut. Die Menüführung sieht sehr gut aus, und muss noch umgesetzt werden. Ich habe dafür schon ein Ticket angelegt. Möchtest du das selber implementieren, oder soll das jemand anderem zugewiesen werden?
Neben der Menüführung hatte ich mir eigentlich gedacht, dass in diesem Ticket auch noch die Ui innerhalb des Editors festgelegt werden sollte. Deshalb würde ich dieses Ticket wieder auf "in Progress" setzen. (Falls ich das nur übersehen habe, setz das Ticket einfach wieder auf done)

**Comment by sani-sun** [comment]
Hey Max, wenn es niemanden stört würde ich dann auch die Implementierung übernehmen. Die UI innerhalb des Editors mache ich noch :) das habe ich verplant

**Comment by maxDierschke** [comment]
Okay Perfekt, ich habe schon einen branch angelegt, damit nicht alle auf den dev branches arbeiten, sondern feature branches benutzt werden.
