### ISSUE TITLE
Implement PathFindingController

### ISSUE THREAD

**Issue by machinegunflows** [machinegunflows/LogiSim#25]
Controller which contains the logic for the pathfinding

**Comment by machinegunflows** [comment]
### Notes:
- `public NavMeshSurface surface`;
- `public void buildNavMesh()`;
- Liste von Destinations: `public Destination[] destinations`;
- `private NavMeshPath calculateShortestPath(V3 start, V3 stop)`;
- `private void moveEntity()`; // Bewegt entity oder aufruf an Mosim
- (Rückgabewert klären): `public Path getShortestPath()`;
- `public Double getDistance()`;

**Comment by jonasbuehrle** [comment]
`public Double getDistance()` - getDistance should either be a method of a destination or the path, path got the method calculateLength for this
