### ISSUE TITLE
Change movement from setDestination to NavMeshPath

### ISSUE THREAD

**Issue by machinegunflows** [machinegunflows/LogiSim#46]

**Comment by jonasbuehrle** [comment]
Paths have no corners, debug Path and compare to demo project. May NavMesh.AllAreas is wrong.

**Comment by machinegunflows** [comment]
Still not properly working. Some paths will not move the NavMeshAgent.

remainingDistance = infinity can be observed when the NavMeshAgent is not moving

Maybe we have to change the targeting form path to waypoints of the path

**Comment by machinegunflows** [comment]
Solved with targetDestination of Path
